name: Deploy to Google Cloud Run

on:
  push:
    
    
branches:
      - main

jobs:
  deploy:
    
   
runs-on: ubuntu-latest
environment: hw-prod
    steps:
      # Verificar o código no repositório
      - name: Check out the code
        uses: actions/checkout@v2

      # Configurar o Google Cloud SDK
      
 
- name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          
      
version: 'latest'
          
  
project_id: ${{ secrets.GCP_PROJECT_ID }}
          
          

  
service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      

     
# Autenticar no Google Cloud
      
      
- name: Authenticate to Google Cloud
        
   
run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_CREDENTIALS }}

      # Construir e enviar a imagem para o Container Registry
      - name: Build and push Docker image
        
   
run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }}
          gcloud builds submit --tag $IMAGE_NAME

     

      
 
# Fazer deploy no Google Cloud Run
      - name: Deploy to Cloud Run
        
     
run: |
          gcloud run deploy my-app \
            --image $IMAGE_NAME \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
